version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "org.jenkins-ci.main:jenkins-core"
    target-branch: master
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
